function [fitresult, gof] = createFit1(alpha, Cx_a)
%CREATEFIT1(ALPHA,CX_A)
%  Create a fit.
%
%  Data for 'Line' fit:
%      X Input : alpha
%      Y Output: Cx_a
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2015 10:52:53


%% Fit: 'Line'.
[xData, yData] = prepareCurveData( alpha, Cx_a );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Line' );
h = plot( fitresult, xData, yData );
legend( h, 'Cx^a vs. alpha', 'Line', 'Location', 'NorthEast' );
% Label axes
xlabel alpha
ylabel Cx^a
grid on


