function [fitresult, gof] = createFit1(ro, H)
%CREATEFIT1(RO,H)
%  Create a fit.
%
%  Data for 'Line' fit:
%      X Input : ro
%      Y Output: H
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2015 11:30:21


%% Fit: 'Line'.
[xData, yData] = prepareCurveData( ro, H );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'Line' );
h = plot( fitresult, xData, yData );
legend( h, 'H vs. ro', 'Line', 'Location', 'NorthEast' );
% Label axes
xlabel('Плотность воздуха');
ylabel('Высота, м');
grid on


