function [fitresult, gof] = createFit1(alpha, cd)
%CREATEFIT1(ALPHA,CD)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alpha
%      Y Output: cd
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2015 14:28:09


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alpha, cd );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'cd vs. alpha', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel alpha
ylabel cd
grid on


