function [fitresult, gof] = createFit(alpha, C_mA)
%CREATEFIT(ALPHA,C_MA)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : alpha
%      Y Output: C_mA
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Oct-2015 14:38:53


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( alpha, C_mA );

% Set up fittype and options.
ft = fittype( 'poly9' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'C_mA vs. alpha', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel alpha
ylabel C_mA
grid on


